<?php
/**
 * @file
 * Creates a block with the inbox icon and username for the FCMTA website
 * This block is placed in the upper right corner in FCMTA website
 * 
 */

/**
 * Implements hook_block_info()
 */

function fcmta_inbox_block_info(){
  $blocks['fcmta_inbox'] =  array(
    'info' => 'FCMTA user and inbox',
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */

function fcmta_inbox_block_view($delta = ''){
  if ($delta == 'fcmta_inbox') {
    $block['subject'] = '';
    $block['content'] = fcmta_inbox_generate();
    return $block;
  }
}

/*
 * Generates content for block fcmta_inbox
 */

 // Block for anonymous user
function fcmta_inbox_generate(){
  if (!user_is_logged_in()) {
    return l("Registered user login","/user");
  }
  
  global $user;
  $u = user_load($user->uid);

  $inbox_color = 'black';
  if (isset($u->field_inbox[LANGUAGE_NONE][0]['value']) && $u->field_inbox[LANGUAGE_NONE][0]['value']){
    $inbox_color = 'red';
  }
  $content = array(
    'inbox' => array(
      '#markup' => '<i class="fa fa-inbox fa-lg"></i> ',
      '#prefix' => '<a href="/message-board" style="color:' . $inbox_color . '">',
      '#suffix' => '</a>',
    ),
    'user' => array(
      '#markup' => l($user->name . ' ', '/user/'. $user->uid),
    ),
    'logout' => array (
      '#markup' => l('Logout', '/user/logout'),
    ),
  );
  return $content;
}